add bootstrap script

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -4,4 +4,10 @@ echo "-----------------------------------------------------------"
 echo "> Running ktlint checks locally before push..."
 echo "-----------------------------------------------------------"
 
-./gradlew ktlintCheck
+./gradlew ktlintCheck --no-configuration-cache --stacktrace
+
+status=$?
+
+# return 1 exit code if running checks fails
+[ $status -ne 0 ] && exit 1
+exit 0
